spring:
  datasource:
    #type: com.alibaba.druid.pool.DruidDataSource 采用DRUID的startup方式
    #driver-class-name: com.mysql.jdbc.Driver 系统自动根据URL判断
    url: jdbc:mysql://47.98.113.120:3306/db_study?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull
    username: root
    password: Cadillac123!@#
  #时间戳统一转换
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

server:
    port: 18080
    servlet:
      context-path: /api/study

springfox.documentation.swagger.v2.path: /api-docs


      
      