mybatis:
  mapper-locations: classpath*:com/study/**/mappers/*.xml,classpath*:com/fasterapp/**/mappers/*.xml  #注意：一定要对应mapper映射xml文件的所在路径
  configuration:
      log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

#pagehelper分页插件
pagehelper:
    helperDialect: mysql
    reasonable: false
    supportMethodsArguments: true
    params: count=countSql

logging:
  config: classpath:log4j2.xml


fasterapp:
  logger:
    headers: user_id,user_name,token

